version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: globant-api
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5434
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=caballo
      - POSTGRES_DB=globant_db
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=caballo
      - POSTGRES_DB=globant_db
    ports:
      - "5432:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: